image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# Default build cache settings to extend from
.build_cached:
  cache:
    key: "gradle-build"
    paths:
      # Only cache the gradle directory, as we do not use a shared cache
      - .gradle/
    policy: pull

build-bookshelf-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: build
  script:
    gradle bookshelf-microservice:assemble bookshelf-microservice:testClasses

checkStyle-bookshelf-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle bookshelf-microservice:checkstyleMain bookshelf-microservice:checkStyleTest
  allow_failure: true


PMD-bookshelf-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle bookshelf-microservice:pmdMain
  allow_failure: true

#test-bookshelf-microservice:
#  extends:
#    - .build_cached
#  needs:
#    - gradle_build
#  dependencies:
#    - gradle_build
#  stage: test
#  script:
#    - gradle bookshelf-microservice:test bookshelf-microservice:jacocoTestReport
#    - cat bookshelf-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
#  coverage: /([0-9]{1,3})%/

